// types of dialog
#define DSM                                                                     DIALOG_STYLE_MSGBOX
#define DSL                                                                     DIALOG_STYLE_LIST
#define DSI                                                                     DIALOG_STYLE_INPUT
#define DSP                                                                     DIALOG_STYLE_PASSWORD
#define DST																		DIALOG_STYLE_TABLIST
#define DSTH																	DIALOG_STYLE_TABLIST_HEADERS