// colors
#define AQUA        														    0x00FFFFFF
#define BLACK        															0x000000FF
#define BLUE         															0x0000FFFF
#define GRAY         															0x80808088
#define GREEN    															    0x008000FF
#define LIGHT_GRAY                                                              0x6E7F8066
#define LIME     															    0x00FF00FF
#define ORANGE                                                                  0xF47721FF
#define PINK                                                                    0xFFA2FFFF
#define RED     															    0xFF0000FF
#define REDa                                                                    0xEB1D12CC // a - admin
#define WHITE        															0xFFFFFFFF
#define YELLOW    															    0xFFFF00FF

#define ADMIN_COLOR                                                             0x65FF4DFF
#define PLAYER_COLOR                                                            0xEF2E2EFF
#define MAFIA_COLOR                                                             0xFF4D65FF

#define PINK1                                                                   0xFFA2FFFF
#define PINK2                                                                   0xFFA2FFDD
#define PINK3                                                                   0xFFA2FFBB
#define PINK4                                                                   0xFFA2FF99
#define PINK5                                                                   0xFFA2FF77

#define WHITE1                                                                  0xFFFFFFFF
#define WHITE2                                                                  0xFFFFFFDD
#define WHITE3                                                                  0xFFFFFFBB
#define WHITE4                                                                  0xFFFFFF99
#define WHITE5                                                                  0xFFFFFF77