// constants
#define SQL_HOST                                                                "localhost"
#define SQL_USER                                                                "root"
#define SQL_DB                                                                  "bad mafia rp"
#define SQL_PASS                                                                ""

// info sevrver
#define SERVER_NAME 															"Mafia Role Play"
#define SERVER_VERSION 															"Role Play"
#define SERVER_MAP            										            "San Andreas"
#define SERVER_WEBSITE 															"mafia-rp.su"
#define SERVER_WEBSITE_DONATE       									        "mafia-rp.su/donate"
#define SERVER_FORUM                										    "forum.mafia-rp.su"
#define SERVER_GROUP                  										    "vk.com/mafiarpsamp"
#define SERVER_LANGUAGE                 										"Russian"